### ISSUE TITLE
Documentation is too much poor

### ISSUE THREAD

**Issue by Snegirekk** [piemekanika/is-eleven#5]
Actually the doc is missing some important examples of usage. What will be returned by the function in such case `isEleven('eleven')` for example? Looks like it should be 'true', but it's not so clear in the docs.

**Comment by piemekanika** [comment]
This is interesting. Does 'eleven' actually equals 11? And should this library work with other languages like `isEleven('elf'); // true` or not? 

Docs will be improved soon anyway.

**Comment by Snegirekk** [comment]
'eleven' is actually eleven, so expected result of function `isEleven('eleven')` is `true` imo

**Comment by dvgololobov** [comment]
> 'eleven' is actually eleven, so expected result of function `isEleven('eleven')` is `true` imo

this feature needs language file...

**Comment by piemekanika** [comment]
> 'eleven' is actually eleven, so expected result of function `isEleven('eleven')` is `true` imo

The problem here is that no language works this way. Let's say we have a function called `isInteger`, do you expect `isInteger('integere')` to be true?

Speaking of JS, there is a method `isFinite`, but `isFinite('Finite')` is actually false.

**Comment by Snegirekk** [comment]
> Speaking of JS, there is a method isFinite, but isFinite('Finite') is actually false.

Actually it's a kind of unexpected

**Comment by Snegirekk** [comment]
Anyway the issue is related to the docs only, it's not a feature request. As you've updated the docs, I think I could close that. (unfortunately there is no a PR that i could refer for)
